### ISSUE TITLE
Yo, did you guys get money from Macho??

### ISSUE THREAD

**Issue by shade** [Lcunha25/Food2Fable#1]
Cuz we didn't...

/stablewallet team

**Comment by HoangDieuAnh** [comment]
We didn't, they said they will follow up this week

**Comment by matt-src** [comment]
I'm pretty sure they exit scammed lol
/tofurocks, benevolent dictator for life, team stablewallet team

**Comment by shade** [comment]
@HoangDieuAnh , pls let us know when they follow up.

**Comment by shade** [comment]
We got paid.
